apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoauyof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoauyof
  template:
    metadata:
      labels:
        app: yoauyof
    spec:
      containers:
      - image: okteto.dev/yoauyof:latest
        name: yoauyof
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "37e9de04-dd78-4a2f-b418-d169cb2ac621"
        - name: Vless_Path
          value: "/vlseek"
        - name: Vmess_UUID
          value: "37e9de04-dd78-4a2f-b418-d169cb2ac621"
        - name: Vmess_Path
          value: "/vmpopular"
        - name: Share_Path
          value: "/v2link"
